name: Bambocafe
favicon: null
layout_spectrum: 0.07041397574357688
typography_spectrum: 0.55936952191405
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.22048733662813902
  lightness: 0.30449408246204257
  saturation: 0.9997772036585957
  rhythmicContrast: 0.9570178431458771
purpose: []
